### ISSUE TITLE
Add support for ClusterIssuer

### ISSUE THREAD

**Issue by gravufo** [smallstep/step-issuer#6]
It would be very nice to support ClusterIssuer so that we don't have to create a StepIssuer in every single namespace we have :)

Thanks!

**Comment by ghoben** [comment]
Are there any plans to support a "ClusterIssuer" for the step-issuer @maraino?

**Comment by maraino** [comment]
@ghoben Yes, but I haven't look into this yet, and I don't know what is required, and how long is going to take.

**Comment by Elegant996** [comment]
`StepIssuer` is the `kind` similar to kind `Issuer` from `cert-manager`. Therefore, a new `kind` would need to be created, possibly called `StepClusterIssuer`, in this case there is no "support" to be added.

The work involved should be similar to that of `Issuer` vs. `ClusterIssuer` from `cert-manager`.

**Comment by carpenike** [comment]
Just checking to see if this is going to be added to the roadmap?

**Comment by maraino** [comment]
This is currently in our backlog, so no priorities have been added yet, I guess the implementation would be similar to the Issuer, so a PR would be welcome.

**Comment by chris2k20** [comment]
Any news on that? I would very much appreciate this, as it would be extremely helpful for our cluster.

On the occasion: Thank you for your time spending on this project in general. Very good job.

**Comment by lukasmrtvy** [comment]
@chris2k20 https://github.com/smallstep/step-issuer/pull/15

**Comment by maraino** [comment]
@chris2k20 @wzrdtales I'm right now on vacation. I will look at this when I get back.

**Comment by lukasmrtvy** [comment]
@maraino any progress? ty

**Comment by wzrdtales** [comment]
no worries :), we and our customers for whom we did those adjustments are not really waiting for you, we're using our own containers and hosted solutions. But the community certainly already is running for it.

**Comment by wzrdtales** [comment]
no worries :), we and our customers for whom we did those adjustments are not really waiting for you, we're using our own containers and hosted solutions. But the community certainly already is running for it.

everyone waiting can just build the container and use this helm chart to make it work https://wzrdtales.github.io/smallstep-helm-charts/

**Comment by Cpcrook** [comment]
Nice job @wzrdtales 

Confirming that this is in a functional state for anyone else who was wondering.  Rather than the aforementioned helm chart, I just re-used my `StepIssuer` manifest with minor modifications to deploy a cluster issuer (deployed to a non-default namespace) after applying the [CRD](https://raw.githubusercontent.com/smallstep/step-issuer/master/config/crd/bases/certmanager.step.sm_stepclusterissuers.yaml): 

* Adding a namespace to the `passwordRef`
* Updating `kind` to `StepClusterIssuer`
* Updating `name` to `step-cluster-issuer` (in my case)

On the `Certificate` resource side in order to test cert issuance in the `default` namespace:

* Updated `issuerRef.kind` to `StepClusterIssuer`
* Updated `issuerRef.name` to match my cluster issuer: `step-cluster-issuer`

The cert was successfully issued across namespaces.

**Comment by maraino** [comment]
Closing as this was fixed with https://github.com/smallstep/step-issuer/pull/15 and has been available since v0.5.0
